CREATE TABLE CLASSIFICADOR (
    NOMCURT VARCHAR(25) PRIMARY KEY,
    NOM VARCHAR(50) NOT NULL
);

CREATE TABLE REPETICIO (
    ID_DATASET NUMBER,
    NUM NUMBER,
    PRIMARY KEY (ID_DATASET, NUM),
    CONSTRAINT fk_repeticio_dataset FOREIGN KEY (ID_DATASET)
        REFERENCES DATASET(ID)
);

CREATE TABLE EXPERIMENT (
    ID_DATASET NUMBER,
    NOM_CURT_CLASSIFICADOR VARCHAR(50),
    NUM_REPETICIO NUMBER,
    ACCURACY NUMBER,
    F_SCORE NUMBER,
    DATA DATE,
    PRIMARY KEY (ID_DATASET, NOM_CURT_CLASSIFICADOR, NUM_REPETICIO),
    CONSTRAINT fk_experiment_classificador2 FOREIGN KEY (NOM_CURT_CLASSIFICADOR)
        REFERENCES CLASSIFICADOR(NOMCURT),
    CONSTRAINT fk_experiment_repeticio FOREIGN KEY (ID_DATASET, NUM_REPETICIO)
        REFERENCES REPETICIO(ID_DATASET, NUM)
);

CREATE TABLE PARAMETERS (
    NOM_CURT_CLASSIFICADOR VARCHAR(25),
    VALORS Vector,
    PRIMARY KEY (NOM_CURT_CLASSIFICADOR, VALORS),
    CONSTRAINT fk_experiment_classificador FOREIGN KEY (NOM_CURT_CLASSIFICADOR)
        REFERENCES CLASSIFICADOR(NOMCURT) 
);